#set_property SEVERITY {Warning} [get_drc_checks RTSTAT-2]
#时钟信号连接
#create_clock -period 10.000 [get_ports clk]
set_property PACKAGE_PIN AC19 [get_ports clk]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets clk]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]

#reset
set_property PACKAGE_PIN Y3 [get_ports resetn]

#LED
set_property PACKAGE_PIN K23 [get_ports {led[0]}]
set_property PACKAGE_PIN J21 [get_ports {led[1]}]
set_property PACKAGE_PIN H23 [get_ports {led[2]}]
set_property PACKAGE_PIN J19 [get_ports {led[3]}]
set_property PACKAGE_PIN G9 [get_ports {led[4]}]
set_property PACKAGE_PIN J26 [get_ports {led[5]}]
set_property PACKAGE_PIN J23 [get_ports {led[6]}]
set_property PACKAGE_PIN J8 [get_ports {led[7]}]
set_property PACKAGE_PIN H8 [get_ports {led[8]}]
set_property PACKAGE_PIN G8 [get_ports {led[9]}]
set_property PACKAGE_PIN F7 [get_ports {led[10]}]
set_property PACKAGE_PIN A4 [get_ports {led[11]}]
set_property PACKAGE_PIN A5 [get_ports {led[12]}]
set_property PACKAGE_PIN A3 [get_ports {led[13]}]
set_property PACKAGE_PIN D5 [get_ports {led[14]}]
set_property PACKAGE_PIN H7 [get_ports {led[15]}]

#led_rg 0/1
set_property PACKAGE_PIN G7 [get_ports {led_rg0[0]}]
set_property PACKAGE_PIN F8 [get_ports {led_rg0[1]}]
set_property PACKAGE_PIN B5 [get_ports {led_rg1[0]}]
set_property PACKAGE_PIN D6 [get_ports {led_rg1[1]}]

#NUM
set_property PACKAGE_PIN D3  [get_ports {num_csn[7]}]
set_property PACKAGE_PIN D25 [get_ports {num_csn[6]}]
set_property PACKAGE_PIN D26 [get_ports {num_csn[5]}]
set_property PACKAGE_PIN E25 [get_ports {num_csn[4]}]
set_property PACKAGE_PIN E26 [get_ports {num_csn[3]}]
set_property PACKAGE_PIN G25 [get_ports {num_csn[2]}]
set_property PACKAGE_PIN G26 [get_ports {num_csn[1]}]
set_property PACKAGE_PIN H26 [get_ports {num_csn[0]}]

set_property PACKAGE_PIN C3 [get_ports {num_a_g[0]}]
set_property PACKAGE_PIN E6 [get_ports {num_a_g[1]}]
set_property PACKAGE_PIN B2 [get_ports {num_a_g[2]}]
set_property PACKAGE_PIN B4 [get_ports {num_a_g[3]}]
set_property PACKAGE_PIN E5 [get_ports {num_a_g[4]}]
set_property PACKAGE_PIN D4 [get_ports {num_a_g[5]}]
set_property PACKAGE_PIN A2 [get_ports {num_a_g[6]}]
#set_property PACKAGE_PIN C4 :DP

#switch
set_property PACKAGE_PIN AC21 [get_ports {switch[7]}]
set_property PACKAGE_PIN AD24 [get_ports {switch[6]}]
set_property PACKAGE_PIN AC22 [get_ports {switch[5]}]
set_property PACKAGE_PIN AC23 [get_ports {switch[4]}]
set_property PACKAGE_PIN AB6  [get_ports {switch[3]}]
set_property PACKAGE_PIN W6   [get_ports {switch[2]}]
set_property PACKAGE_PIN AA7  [get_ports {switch[1]}]
set_property PACKAGE_PIN Y6   [get_ports {switch[0]}]

#btn_key
set_property PACKAGE_PIN V8  [get_ports {btn_key_col[0]}]
set_property PACKAGE_PIN V9  [get_ports {btn_key_col[1]}]
set_property PACKAGE_PIN Y8  [get_ports {btn_key_col[2]}]
set_property PACKAGE_PIN V7  [get_ports {btn_key_col[3]}]
set_property PACKAGE_PIN U7  [get_ports {btn_key_row[0]}]
set_property PACKAGE_PIN W8  [get_ports {btn_key_row[1]}]
set_property PACKAGE_PIN Y7  [get_ports {btn_key_row[2]}]
set_property PACKAGE_PIN AA8 [get_ports {btn_key_row[3]}]

#btn_step
set_property PACKAGE_PIN Y5 [get_ports btn_step[0]]
set_property PACKAGE_PIN V6 [get_ports btn_step[1]]

#SPI flash
set_property PACKAGE_PIN P20 [get_ports SPI_CLK]
set_property PACKAGE_PIN R20 [get_ports SPI_CS]
set_property PACKAGE_PIN P19 [get_ports SPI_MISO]
set_property PACKAGE_PIN N18 [get_ports SPI_MOSI]

#mac phy connect
set_property PACKAGE_PIN AB21 [get_ports mtxclk_0]
set_property PACKAGE_PIN AA19 [get_ports mrxclk_0]
set_property PACKAGE_PIN AA15 [get_ports mtxen_0]
set_property PACKAGE_PIN AF18 [get_ports {mtxd_0[0]}]
set_property PACKAGE_PIN AE18 [get_ports {mtxd_0[1]}]
set_property PACKAGE_PIN W15 [get_ports {mtxd_0[2]}]
set_property PACKAGE_PIN W14 [get_ports {mtxd_0[3]}]
set_property PACKAGE_PIN AB20 [get_ports mtxerr_0]
set_property PACKAGE_PIN AE22 [get_ports mrxdv_0]
set_property PACKAGE_PIN V1 [get_ports {mrxd_0[0]}]
set_property PACKAGE_PIN V4 [get_ports {mrxd_0[1]}]
set_property PACKAGE_PIN V2 [get_ports {mrxd_0[2]}]
set_property PACKAGE_PIN V3 [get_ports {mrxd_0[3]}]
set_property PACKAGE_PIN W16 [get_ports mrxerr_0]
set_property PACKAGE_PIN Y15 [get_ports mcoll_0]
set_property PACKAGE_PIN AF20 [get_ports mcrs_0]
set_property PACKAGE_PIN W3 [get_ports mdc_0]
set_property PACKAGE_PIN W1 [get_ports mdio_0]
set_property PACKAGE_PIN AE26 [get_ports phy_rstn]

#uart
set_property PACKAGE_PIN F23 [get_ports UART_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX]
set_property PACKAGE_PIN H19 [get_ports UART_TX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX]

#debug uart
set_property PACKAGE_PIN M25 [get_ports UART_RX2]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX2]
set_property PACKAGE_PIN P25 [get_ports UART_TX2]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX2]

#nand flash
set_property PACKAGE_PIN V19 [get_ports NAND_CLE]
set_property PACKAGE_PIN W20 [get_ports NAND_ALE]
set_property PACKAGE_PIN AA25 [get_ports NAND_RDY]
set_property PACKAGE_PIN AA24 [get_ports NAND_RD]
set_property PACKAGE_PIN AB24 [get_ports NAND_CE]
set_property PACKAGE_PIN AA22 [get_ports NAND_WR]
set_property PACKAGE_PIN W19 [get_ports {NAND_DATA[7]}]
set_property PACKAGE_PIN Y20 [get_ports {NAND_DATA[6]}]
set_property PACKAGE_PIN Y21 [get_ports {NAND_DATA[5]}]
set_property PACKAGE_PIN V18 [get_ports {NAND_DATA[4]}]
set_property PACKAGE_PIN U19 [get_ports {NAND_DATA[3]}]
set_property PACKAGE_PIN U20 [get_ports {NAND_DATA[2]}]
set_property PACKAGE_PIN W21 [get_ports {NAND_DATA[1]}]
set_property PACKAGE_PIN AC24 [get_ports {NAND_DATA[0]}]

#ejtag
set_property PACKAGE_PIN J18 [get_ports EJTAG_TRST]
set_property PACKAGE_PIN K18 [get_ports EJTAG_TCK]
set_property PACKAGE_PIN K20 [get_ports EJTAG_TDI]
set_property PACKAGE_PIN K22 [get_ports EJTAG_TMS]
set_property PACKAGE_PIN K21 [get_ports EJTAG_TDO]


set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports resetn]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rg0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rg1[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_a_g[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_csn[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_key_col[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_key_row[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_step[*]}]

set_property IOSTANDARD LVCMOS33 [get_ports SPI_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CS]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CLK]

set_property IOSTANDARD LVCMOS33 [get_ports {mrxd_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mtxd_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rstn]
set_property IOSTANDARD LVCMOS33 [get_ports mtxerr_0]
set_property IOSTANDARD LVCMOS33 [get_ports mtxen_0]
set_property IOSTANDARD LVCMOS33 [get_ports mtxclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports mrxerr_0]
set_property IOSTANDARD LVCMOS33 [get_ports mcoll_0]
set_property IOSTANDARD LVCMOS33 [get_ports mcrs_0]
set_property IOSTANDARD LVCMOS33 [get_ports mdc_0]
set_property IOSTANDARD LVCMOS33 [get_ports mdio_0]
set_property IOSTANDARD LVCMOS33 [get_ports mrxclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports mrxdv_0]

set_property IOSTANDARD LVCMOS33 [get_ports NAND_CLE]
set_property IOSTANDARD LVCMOS33 [get_ports NAND_ALE]
set_property IOSTANDARD LVCMOS33 [get_ports NAND_RDY]
set_property IOSTANDARD LVCMOS33 [get_ports NAND_RD]
set_property IOSTANDARD LVCMOS33 [get_ports NAND_CE]
set_property IOSTANDARD LVCMOS33 [get_ports NAND_WR]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports EJTAG_TRST]
set_property IOSTANDARD LVCMOS33 [get_ports EJTAG_TCK]
set_property IOSTANDARD LVCMOS33 [get_ports EJTAG_TDI]
set_property IOSTANDARD LVCMOS33 [get_ports EJTAG_TMS]
set_property IOSTANDARD LVCMOS33 [get_ports EJTAG_TDO]
# EJTAG_TCK is routed through the design clocking resources; the former
# EJTAG_TCK_IBUF net-level exception referred to a net that no longer exists.

# VGA interface (RGB444, 640x480 color-bar test)
set_property PACKAGE_PIN T3 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN T2 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN U2 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN U4 [get_ports {vga_r[3]}]

set_property PACKAGE_PIN R2 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN R1 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN U1 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN R5 [get_ports {vga_g[3]}]

set_property PACKAGE_PIN P5 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN N1 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN P1 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN P3 [get_ports {vga_b[3]}]

set_property PACKAGE_PIN U5 [get_ports vga_hsync]
set_property PACKAGE_PIN U6 [get_ports vga_vsync]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync]

# OV5640 camera on expansion header J16
# J16-3/4: SCCB; J16-5..12: D0..D7; J16-13/14/15: PCLK/VSYNC/HREF;
# J16-16/17: RESET_N/PWDN.  J16-18 is intentionally unused.
set_property PACKAGE_PIN V26  [get_ports cam_scl]
set_property PACKAGE_PIN U24  [get_ports cam_sda]
set_property PACKAGE_PIN W25  [get_ports {cam_d[0]}]
set_property PACKAGE_PIN W26  [get_ports {cam_d[1]}]
set_property PACKAGE_PIN Y25  [get_ports {cam_d[2]}]
set_property PACKAGE_PIN Y26  [get_ports {cam_d[3]}]
set_property PACKAGE_PIN AB25 [get_ports {cam_d[4]}]
set_property PACKAGE_PIN AB26 [get_ports {cam_d[5]}]
set_property PACKAGE_PIN Y23  [get_ports {cam_d[6]}]
set_property PACKAGE_PIN AC26 [get_ports {cam_d[7]}]
set_property PACKAGE_PIN Y22  [get_ports cam_pclk]
set_property PACKAGE_PIN V21  [get_ports cam_vsync]
set_property PACKAGE_PIN V16  [get_ports cam_href]
set_property PACKAGE_PIN AA23 [get_ports cam_rst_n]
set_property PACKAGE_PIN V14  [get_ports cam_pwdn]

set_property IOSTANDARD LVCMOS33 [get_ports {cam_scl cam_sda cam_d[*] cam_pclk cam_vsync cam_href cam_rst_n cam_pwdn}]
set_property PULLUP TRUE [get_ports {cam_scl cam_sda}]
create_clock -period 10.000 -name cam_pclk [get_ports cam_pclk]

# Mechanical-arm UART TX on expansion header J15-4 / FPGA_EXT0_IO1.
set_property PACKAGE_PIN T19 [get_ports ARM_UART_TX]
set_property IOSTANDARD LVCMOS33 [get_ports ARM_UART_TX]

create_clock -period 40.000 -name mrxclk_0 -waveform {0.000 20.000} [get_ports mrxclk_0]
create_clock -period 40.000 -name mtxclk_0 -waveform {0.000 20.000} [get_ports mtxclk_0]

set_false_path -from [get_clocks clk_pll_i] -to [get_clocks clk_out2_clk_pll_33]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks clk_pll_i]
set_false_path -from [get_clocks clk] -to [get_clocks clk_out2_clk_pll_33]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks clk]
set_false_path -from [get_clocks cam_pclk] -to [get_clocks clk_out2_clk_pll_33]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks cam_pclk]
set_false_path -from [get_clocks mrxclk_0] -to [get_clocks clk_out2_clk_pll_33]
set_false_path -from [get_clocks mtxclk_0] -to [get_clocks clk_out2_clk_pll_33]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks clk_out1_clk_pll_33]
set_false_path -from [get_clocks clk_out1_clk_pll_33] -to [get_clocks clk_out2_clk_pll_33]
# VGA runs from clk_out3.  Its crossings to CONFREG/CPU are explicit
# synchronizers, and the camera/VDMA crossings use dual-clock storage.
set_false_path -from [get_clocks clk_out3_clk_pll_33] -to [get_clocks clk_out2_clk_pll_33]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks clk_out3_clk_pll_33]
set_false_path -from [get_clocks clk_out3_clk_pll_33] -to [get_clocks clk_out1_clk_pll_33]
set_false_path -from [get_clocks clk_out1_clk_pll_33] -to [get_clocks clk_out3_clk_pll_33]
set_false_path -from [get_clocks cam_pclk] -to [get_clocks clk_out3_clk_pll_33]
set_false_path -from [get_clocks clk_out3_clk_pll_33] -to [get_clocks cam_pclk]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks mrxclk_0]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks mrxclk_0]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks mtxclk_0]
set_false_path -from [get_clocks clk_out2_clk_pll_33] -to [get_clocks mtxclk_0]


# LCD_STAGE1_NT35510 - ALIENTEK 4.3-inch TFTLCD, 16-bit 8080 bus
set_property PACKAGE_PIN H9  [get_ports {LCD_DB[0]}]
set_property PACKAGE_PIN K17 [get_ports {LCD_DB[1]}]
set_property PACKAGE_PIN J20 [get_ports {LCD_DB[2]}]
set_property PACKAGE_PIN M17 [get_ports {LCD_DB[3]}]
set_property PACKAGE_PIN L17 [get_ports {LCD_DB[4]}]
set_property PACKAGE_PIN L18 [get_ports {LCD_DB[5]}]
set_property PACKAGE_PIN L15 [get_ports {LCD_DB[6]}]
set_property PACKAGE_PIN M15 [get_ports {LCD_DB[7]}]
set_property PACKAGE_PIN M16 [get_ports {LCD_DB[8]}]
set_property PACKAGE_PIN L14 [get_ports {LCD_DB[9]}]
set_property PACKAGE_PIN M14 [get_ports {LCD_DB[10]}]
set_property PACKAGE_PIN F22 [get_ports {LCD_DB[11]}]
set_property PACKAGE_PIN G22 [get_ports {LCD_DB[12]}]
set_property PACKAGE_PIN G21 [get_ports {LCD_DB[13]}]
set_property PACKAGE_PIN H24 [get_ports {LCD_DB[14]}]
set_property PACKAGE_PIN J16 [get_ports {LCD_DB[15]}]

set_property PACKAGE_PIN H18 [get_ports LCD_CS_N]
set_property PACKAGE_PIN K16 [get_ports LCD_RS]
set_property PACKAGE_PIN L8  [get_ports LCD_WR_N]
set_property PACKAGE_PIN K8  [get_ports LCD_RD_N]
set_property PACKAGE_PIN J25 [get_ports LCD_RST_N]
set_property PACKAGE_PIN J15 [get_ports LCD_BL]

set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DB[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_CS_N LCD_RS LCD_WR_N LCD_RD_N LCD_RST_N LCD_BL}]
set_property DRIVE 8 [get_ports {LCD_DB[*]}]
set_property DRIVE 8 [get_ports {LCD_CS_N LCD_RS LCD_WR_N LCD_RD_N LCD_RST_N LCD_BL}]
set_property SLEW SLOW [get_ports {LCD_DB[*]}]
set_property SLEW SLOW [get_ports {LCD_CS_N LCD_RS LCD_WR_N LCD_RD_N LCD_RST_N LCD_BL}]
