// Auto-generated by gen_descriptors.py - mnist_lenet_v1 descriptors
// Do not hand-edit.

#ifndef MNIST_LENET_DESC_H
#define MNIST_LENET_DESC_H

#include "npu_descriptor.h"

#define MNIST_LENET_NUM_LAYERS 4u

static const npu_layer_desc_t mnist_lenet_descriptors[] = {
    /* L0 */ { {0x00103311u, 0x00122000u, 0x00040001u, 0x001C001Cu, 0x000D000Du, 0x00000000u, 0x00000240u, 0x00000008u} },
    /* L1 */ { {0x00103311u, 0x00122001u, 0x00080004u, 0x000D000Du, 0x00060006u, 0x00000251u, 0x00000491u, 0x00000007u} },
    /* L2 */ { {0x00103311u, 0x00122000u, 0x00100008u, 0x00060006u, 0x00020002u, 0x000004A2u, 0x000006E2u, 0x00000007u} },
    /* L3 */ { {0x01101111u, 0x00000000u, 0x000A0040u, 0x00010001u, 0x00010001u, 0x000006F3u, 0x000007F3u, 0x00000008u} },
};

#endif // MNIST_LENET_DESC_H
