// Auto-generated by gen_descriptors.py - npu_vgg_s1_v1 descriptors
// Do not hand-edit.

#ifndef NPU_VGG_S1_DESC_H
#define NPU_VGG_S1_DESC_H

#include "npu_descriptor.h"

#define NPU_VGG_S1_NUM_LAYERS 6u

static const npu_layer_desc_t npu_vgg_s1_descriptors[] = {
    /* L0 */ { {0x00103311u, 0x00000000u, 0x00100003u, 0x00220022u, 0x00200020u, 0x00000000u, 0x00000240u, 0x00000007u} },
    /* L1 */ { {0x00103311u, 0x00122001u, 0x00100010u, 0x00200020u, 0x00100010u, 0x00000251u, 0x00000491u, 0x00000009u} },
    /* L2 */ { {0x00103311u, 0x00000001u, 0x00200010u, 0x00100010u, 0x00100010u, 0x000004A2u, 0x00000922u, 0x00000008u} },
    /* L3 */ { {0x00103311u, 0x00122001u, 0x00200020u, 0x00100010u, 0x00080008u, 0x00000943u, 0x00001243u, 0x00000008u} },
    /* L4 */ { {0x00103311u, 0x00122001u, 0x00200020u, 0x00080008u, 0x00040004u, 0x00001264u, 0x00001B64u, 0x00000008u} },
    /* L5 */ { {0x01101111u, 0x00000000u, 0x000A0200u, 0x00010001u, 0x00010001u, 0x00001B85u, 0x00002385u, 0x0000000Au} },
};

#endif // NPU_VGG_S1_DESC_H
